// backend/constants/payrollStatus.js
export const PAYROLL_STATUS = {
  DRAFT: 'DRAFT',
  PREPARED: 'PREPARED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  LOCKED: 'LOCKED',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED',
  REJECTED: 'REJECTED'
};

export const ALLOWED_TRANSITIONS = {
  [PAYROLL_STATUS.DRAFT]: [PAYROLL_STATUS.PREPARED, PAYROLL_STATUS.CANCELLED],
  [PAYROLL_STATUS.PREPARED]: [PAYROLL_STATUS.UNDER_REVIEW, PAYROLL_STATUS.DRAFT, PAYROLL_STATUS.CANCELLED],
  [PAYROLL_STATUS.UNDER_REVIEW]: [PAYROLL_STATUS.APPROVED, PAYROLL_STATUS.REJECTED, PAYROLL_STATUS.DRAFT],
  [PAYROLL_STATUS.APPROVED]: [PAYROLL_STATUS.LOCKED, PAYROLL_STATUS.DRAFT],
  [PAYROLL_STATUS.LOCKED]: [PAYROLL_STATUS.PAID, PAYROLL_STATUS.UNLOCKED],
  [PAYROLL_STATUS.PAID]: [PAYROLL_STATUS.COMPLETED],
  [PAYROLL_STATUS.CANCELLED]: [PAYROLL_STATUS.DRAFT],
  [PAYROLL_STATUS.REJECTED]: [PAYROLL_STATUS.DRAFT]
};

// Operations that should be blocked based on status
export const BLOCKED_OPERATIONS = {
  SYNC: [PAYROLL_STATUS.APPROVED, PAYROLL_STATUS.LOCKED, PAYROLL_STATUS.PAID],
  UPDATE_EMPLOYEE: [PAYROLL_STATUS.LOCKED, PAYROLL_STATUS.PAID],
  BULK_UPDATE: [PAYROLL_STATUS.LOCKED, PAYROLL_STATUS.PAID],
  DELETE: [PAYROLL_STATUS.LOCKED, PAYROLL_STATUS.PAID],
  REVERT_TO_DRAFT: [PAYROLL_STATUS.PAID] // Can't revert once paid
};